(define (equal? a b)
	(cond ((and (null? a)
	            (null? b) #t))
	      ((and (symbol? a)
                  (symbol? b)
				  (eq? a b)) #t)
          ((and (list? a)
		        (list? b)) (and (equal? (car a) (car b))
				                (equal? (cdr a) (cdr b))))
		  (else #f)))

;(display (equal? `(apple (pear sauce) orange) `(apple (pear sauce) orange)))
;(newline)
;(display (car ''abc))
(display (car (quote (quote abc))))