(define iteration-times 0)
(define (cbrt-iter guess x)
	(begin
		(set! iteration-times (+ iteration-times 1))
		(if (good-enough? guess x)
			guess
			(cbrt-iter (improve guess x) x))))
(define (improve guess x)
	(/	(+	(/ x (square guess))
			(* 2 guess))
		3))
(define (good-enough? guess x)
	(<	(abs (- (cube guess) x))
		0.001))
(define (square x)
	(* x x))
(define (cube x)
	(* x x x))
(define (abs x)
	(if (< x 0)
		(- x)
		x))
(define (cbrt x)
	(cbrt-iter 1.0 x))
(display (cbrt 8))
(newline)
(display iteration-times)
(newline)
