(define (count-change amount)
	(define (cc amount kinds-of-coins)
		(cond 	((= amount 0) 1)
				((or (< amount 0) (= kinds-of-coins 0)) 0)
				(else (+ (cc amount (- kinds-of-coins 1)) 
						 (cc (- amount (first-nomination kinds-of-coins)) kinds-of-coins)))))
	(define (first-nomination kinds-of-coins)
		(cond 	((= kinds-of-coins 5) 50)
				((= kinds-of-coins 4) 25)
				((= kinds-of-coins 3) 10)
				((= kinds-of-coins 2) 5)
				((= kinds-of-coins 1) 1)))
	(cc amount 5))
(define amount 100)
(display (count-change amount))
(newline)