(define (sqrt x)
	(define (sqrt-iter guess)
		(if (good-enough? guess)
			guess
			(sqrt-iter (improve guess))))
	(define (good-enough? guess)
		(<	(abs (- (square guess) x))	
			0.001))
	(define (improve guess)
		(/	(+ guess (/ x guess))	
			2))
	(define (square x)
		(* x x))
	(sqrt-iter 1.0))
(define N 2)
(display (sqrt N))
(newline)