(display (char? #\c))
(newline)
(display (char<? #\a #\c))
(newline)
(display (char>? #\a #\c))
(newline)
(display (char-upcase #\a))
(newline)
(display (char-ci=? #\a #\A))
(newline)
(display (char-ci<? #\a #\G))