(define x (list 1 2 3 4 5))
(display x)
(newline)
(display (list-ref x 0))
(display (list-ref x 1))
(display (list-ref x 2))
(display (list-ref x 3))
(newline)
(display (list-tail x 2))
(newline)
(display (null? (list)))