(define str1 (string #\a #\b #\c))
(display str1)
(newline)
(define str2 "Hello World!")
(display str2)
(newline)
(display (string-ref str2 1))
(newline)
(display (string-append str2 " Good "
					"Morning "
					"I Love U"))
(newline)
(define a-3-char-long-string (make-string 3))
(display (string? a-3-char-long-string))
(newline)
(string-set! a-3-char-long-string 0 #\W)
(string-set! a-3-char-long-string 1 #\O)
(string-set! a-3-char-long-string 2 #\W)
(display a-3-char-long-string)