(define (f n)
	(define (iter a b c counter)
		(if (= counter 0)
			c
			(iter b c (update-c a b c) (- counter 1))))
	(define (update-c a b c)
		(+	(* c 1)
			(* b 2)
			(* a 3)))
	(cond 	((< n 3)	n)
			(else		(iter 0 1 2 (- n 2)))))
(define N 10)
(display (f N))
(newline)