(define (square x)
	(* x x))
(define (abs x)
	(if (< x 0)
		(- x)
		x))
(define (sqrt-iter guess last-guess x)
	(if (good-enough? guess last-guess)
		guess
		(sqrt-iter (improve guess x) guess x)))
(define (improve guess x)
	(/	(+	guess
			(/ x guess))	
		2))	
;(define (good-enough? guess x)
;	(<	(abs (- (square guess) x))	
;		0.001))
(define (good-enough? guess last-guess)
	(<  (/	(abs (- guess last-guess))
		last-guess)	
	0.001))	
	
(define (sqrt x)
	(sqrt-iter 1.0 0.0 x))
(display (sqrt 1000))
(newline)
